---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: openwisp-postgresql
data:
  POSTGRES_DB: openwisp_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  DJANGO_SECRET_KEY: MY_COMPANY_SECRET_KEY
  DB_HOST: postgresql
  DASHBOARD_DOMAIN: dasboard.openwisp.org openwisp-dashboard.2stacks.net
  CONTROLLER_DOMAIN: controller.openwisp.org openwisp-controller.2stacks.net
  RADIUS_DOMAIN: radius.openwisp.org openwisp-radius.2stacks.net
  TOPOLOGY_DOMAIN: topology.openwisp.org openwisp-topology.2stacks.net
  NGINX_SERVER_NAME_HASH_BUCKET: "64"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
data:
  DJANGO_DEFAULT_FROM_EMAIL: postmaster@example.com
  POSTFIX_ALLOWED_SENDER_DOMAINS: example.com
  POSTFIX_MYHOSTNAME: example.com
  POSTFIX_MYNETWORKS: 10.0.0.0/8
