---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-dashboard
    spec:
      containers:
      - name: openwisp-dashboard
        image: openwisp/openwisp-dashboard:latest
        envFrom:
          - configMapRef:
              name: common-config
        volumeMounts:
          - mountPath: /opt/openwisp/static
            name: openwisp-dashboard-static
          - mountPath: /opt/openwisp/media
            name: openwisp-media-data
          - mountPath: /opt/openwisp/public_html
            name: openwisp-html-data
      volumes:
        - name: openwisp-media-data
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: openwisp-dashboard-static
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: openwisp-html-data
          persistentVolumeClaim:
            claimName: html-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-controller
    spec:
      containers:
      - name: openwisp-controller
        image: openwisp/openwisp-controller:latest
        envFrom:
          - configMapRef:
              name: common-config
        volumeMounts:
          - mountPath: /opt/openwisp/static
            name: openwisp-controller-static
          - mountPath: /opt/openwisp/media
            name: openwisp-media-data
          - mountPath: /opt/openwisp/public_html
            name: openwisp-html-data
      volumes:
        - name: openwisp-media-data
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: openwisp-controller-static
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: openwisp-html-data
          persistentVolumeClaim:
            claimName: html-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-radius
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-radius
    spec:
      containers:
      - name: openwisp-radius
        image: openwisp/openwisp-radius:latest
        envFrom:
          - configMapRef:
              name: common-config
        volumeMounts:
          - mountPath: /opt/openwisp/static
            name: openwisp-radius-static
          - mountPath: /opt/openwisp/public_html
            name: openwisp-html-data
      volumes:
        - name: openwisp-radius-static
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: openwisp-html-data
          persistentVolumeClaim:
            claimName: html-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-topology
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-topology
    spec:
      containers:
      - name: openwisp-topology
        image: openwisp/openwisp-topology:latest
        envFrom:
          - configMapRef:
              name: common-config
        volumeMounts:
          - mountPath: /opt/openwisp/static
            name: openwisp-topology-static
          - mountPath: /opt/openwisp/public_html
            name: openwisp-html-data
      volumes:
        - name: openwisp-topology-static
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: openwisp-html-data
          persistentVolumeClaim:
            claimName: html-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-nginx
    spec:
      containers:
      - name: openwisp-nginx
        image: openwisp/openwisp-nginx:latest
        envFrom:
          - configMapRef:
              name: common-config
        volumeMounts:
          - mountPath: /opt/openwisp/static
            name: openwisp-nginx-static
          - mountPath: /opt/openwisp/media
            name: openwisp-media-data
          - mountPath: /opt/openwisp/public_html
            name: openwisp-html-data
      volumes:
        - name: openwisp-nginx-static
          persistentVolumeClaim:
            claimName: static-pv-claim
        - name: openwisp-media-data
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: openwisp-html-data
          persistentVolumeClaim:
            claimName: html-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-postgresql
    spec:
      containers:
        - name: openwisp-postgresql
          image: mdillon/postgis:10-alpine
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: openwisp-postgres-data
      volumes:
        - name: openwisp-postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openwisp-postfix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openwisp-postfix
    spec:
      containers:
        - name: openwisp-postfix
          image: openwisp-postfix
          envFrom:
            - configMapRef:
                name: postfix-config
          volumeMounts:
            - mountPath: /etc/ssl/mail
              name: openwisp-postfix-data
      volumes:
        - name: openwisp-postfix-data
          persistentVolumeClaim:
            claimName: postfix-pv-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
