apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
      app: openwisp-dashboard
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: openwisp-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
      app: openwisp-controller
spec:
  type: ClusterIP
  ports:
    - port: 8001
  selector:
    app: openwisp-controller
---
apiVersion: v1
kind: Service
metadata:
  name: radius
  labels:
      app: openwisp-radius
spec:
  type: ClusterIP
  ports:
    - port: 8002
  selector:
    app: openwisp-radius
---
apiVersion: v1
kind: Service
metadata:
  name: topology
  labels:
      app: openwisp-topology
spec:
  type: ClusterIP
  ports:
    - port: 8003
  selector:
    app: openwisp-topology
---
apiVersion: v1
kind: Service
metadata:
  name: daphne
  labels:
      app: openwisp-daphne
spec:
  type: ClusterIP
  ports:
    - port: 8004
  selector:
    app: openwisp-daphne
---
apiVersion: v1
kind: Service
metadata:
  name: freeradius
  labels:
      app: openwisp-freeradius
  annotations:
    external-dns.alpha.kubernetes.io/hostname: freeradius.2stacks.net
spec:
  type: LoadBalancer
  ports:
    - name: auth
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: acct
      protocol: UDP
      port: 1813
      targetPort: 1813
  selector:
    app: openwisp-freeradius
---
apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
      app: openwisp-openvpn
  annotations:
    external-dns.alpha.kubernetes.io/hostname: openvpn.2stacks.net
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 1194
      targetPort: 1194
  selector:
    app: openwisp-openvpn
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: openwisp-postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: openwisp-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
   - port: 6379
  selector:
   app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: openwisp-postfix
spec:
  type: ClusterIP
  ports:
   - port: 25
  selector:
   app: openwisp-postfix
---
apiVersion: v1
kind: Service
metadata:
  name: openwisp-nginx
  labels:
    app: openwisp-nginx
spec:
  type: ClusterIP
  ports:
    - name: insecure
      port: 80
    - name: secure
      port: 443
  selector:
   app: openwisp-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-internal
  labels:
    app: openwisp-nginx
spec:
  type: ClusterIP
  ports:
    - name: insecure
      port: 80
  selector:
   app: openwisp-nginx
